// <auto-generated />
using System;
using FPTTelecomBE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FPTTelecomBE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FPTTelecomBE.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("DeviceBonus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceMonthly")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PromotionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpeedDown")
                        .HasColumnType("int");

                    b.Property<int>("SpeedUp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            DeviceBonus = "Modem WiFi 6",
                            Name = "Internet Giga",
                            PriceMonthly = 180000m,
                            PromotionText = "Tặng Modem WiFi 6 + Giảm 50k online + Tặng 1 tháng nếu trả trước 12 tháng",
                            SpeedDown = 300,
                            SpeedUp = 300
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            DeviceBonus = "Modem WiFi 6 + FPT Play Box",
                            Name = "Internet Sky",
                            PriceMonthly = 190000m,
                            PromotionText = "Tặng Modem WiFi 6 + FPT Play Box (combo) + Giảm 50k",
                            SpeedDown = 1000,
                            SpeedUp = 300
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            DeviceBonus = "Modem WiFi 6 + Access Point/Mesh",
                            Name = "Internet Meta",
                            PriceMonthly = 305000m,
                            PromotionText = "Symmetric 1Gbps + WiFi 6 + Mesh/AP tùy F1/F2/F3 + Tặng tháng trả trước",
                            SpeedDown = 1000,
                            SpeedUp = 1000
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            DeviceBonus = "Modem WiFi 6 + FPT Play Box",
                            Name = "Combo Thể Thao Sky",
                            PriceMonthly = 269000m,
                            PromotionText = "Ngoại hạng Anh + FPT Play Box + Modem WiFi 6",
                            SpeedDown = 1000,
                            SpeedUp = 300
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            DeviceBonus = "Modem WiFi 7 + 1 Mesh WiFi 7",
                            Name = "SpeedX2 Pro (WiFi 7)",
                            PriceMonthly = 1099000m,
                            PromotionText = "XGS-PON + WiFi 7 + Mesh WiFi 7 + FPT Play VIP",
                            SpeedDown = 2000,
                            SpeedUp = 2000
                        });
                });

            modelBuilder.Entity("FPTTelecomBE.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("FPTTelecomBE.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AssignedStaffId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedStaffId");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("FPTWifiBE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 29, 15, 45, 13, 92, DateTimeKind.Utc).AddTicks(983),
                            Email = "admin@fptbinhdinh.com",
                            Name = "Admin FPT Bình Định",
                            PasswordHash = "$2a$11$BgCSuZPvr1LuotmqitZ5r.fzaYoU.L.ExtbFTVXUkAJmIuLpW8Z9u",
                            Phone = "0901234567",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("FPTTelecomBE.Models.Registration", b =>
                {
                    b.HasOne("FPTWifiBE.Models.User", "AssignedStaff")
                        .WithMany()
                        .HasForeignKey("AssignedStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FPTTelecomBE.Models.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPTWifiBE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AssignedStaff");

                    b.Navigation("Package");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
